version: "3.7"
services:
  app:
    build:
      args:
        user: developer
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: event-sourcing-demo
    container_name: event-sourcing-demo-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ../:/var/www
    networks:
      - eventsourcingdemo
  db:
    image: mysql:5.7
    container_name: event-sourcing-demo-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: event_sourcing_demo
      MYSQL_ROOT_PASSWORD: veryverysecret
      MYSQL_PASSWORD: veryverysecret
      MYSQL_USER: esdbuser
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
    - 3306:3306
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - eventsourcingdemo
  nginx:
    image: nginx:1.17-alpine
    container_name: event-sourcing-demo-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - eventsourcingdemo

networks:
  eventsourcingdemo:
    driver: bridge
